[workspace]
resolver = "3"
members = [
    "shared",
    "backend",
    "frontend"]

[workspace.dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sqlx = { version = "0.8.6" }
